[package]
name = "swanky-party"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
