[package]
name = "swanky-twopac"
description = "Two-party secure computation using garbled circuits."
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
fancy-garbling.workspace = true
fancy-traits.workspace = true
swanky-adversary.workspace = true
swanky-rng.workspace = true
swanky-block.workspace = true
swanky-channel.workspace = true
swanky-error.workspace = true
swanky-field-binary.workspace = true
swanky-ot-traits.workspace = true

itertools.workspace = true
rand.workspace = true

[dev-dependencies]
fancy-analyzer.workspace = true
fancy-circuits.workspace = true
fancy-plaintext.workspace = true
swanky-ot-chou-orlandi.workspace = true
swanky-ot-alsz-kos.workspace = true

clap.workspace = true
criterion.workspace = true

[[bench]]
name = "semihonest_2pc"
harness = false
