[package]
name = "swanky-twopac"
description = "Two-party secure computation using garbled circuits."
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
fancy-garbling.workspace = true
swanky-adversary.workspace = true
swanky-rng.workspace = true
swanky-block.workspace = true
swanky-channel.workspace = true
swanky-error.workspace = true
swanky-ocelot-error.workspace = true
swanky-ot-traits.workspace = true

itertools.workspace = true
rand.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
swanky-ot-chou-orlandi.workspace = true
swanky-ot-alsz-kos.workspace = true

clap.workspace = true
criterion.workspace = true

[[bench]]
name = "semihonest_2pc"
harness = false
