[workspace]
resolver = "2"
members = [
  "core/adversary",
  "core/channel",
  "core/error",
  "core/party",
  "core/serialization",
  "core/vectoreyes",
  "edge/authenticated-bits",
  "edge/authenticated-garbling",
  "edge/bit-matrix-transpose",
  "edge/block",
  "edge/bytearray-utils",
  "edge/channel-legacy",
  "edge/cointoss",
  "edge/cr-hash",
  "edge/deprecated-bitwise-utils",
  "edge/diet-mac-and-cheese",
  "edge/diet-mac-and-cheese/web-mac-and-cheese/wasm",
  "edge/diet-mac-and-cheese/web-mac-and-cheese/websocket",
  "edge/f-eq",
  "edge/f-rand",
  "edge/fancy-analyzer",
  "edge/fancy-circuits",
  "edge/fancy-garbling",
  "edge/fancy-plaintext",
  "edge/fancy-traits",
  "edge/field",
  "edge/field-binary",
  "edge/field-f61p",
  "edge/field-ff-primes",
  "edge/field-fft",
  "edge/field-test",
  "edge/flatbuffer-build",
  "edge/garbled-nn",
  "edge/humidor",
  "edge/inferno",
  "edge/keyed_arena",
  "edge/mac-n-cheese/compiler",
  "edge/mac-n-cheese/event-log",
  "edge/mac-n-cheese/inspector",
  "edge/mac-n-cheese/ir",
  "edge/mac-n-cheese/runner",
  "edge/mac-n-cheese/sieve-parser",
  "edge/mac-n-cheese/vole",
  "edge/mac-n-cheese/wire-map",
  "edge/malicious-hooks",
  "edge/ocelot-error",
  "edge/oprf-kkrt",
  "edge/oprf-kmprt",
  "edge/oprf-traits",
  "edge/ot-alsz-kos",
  "edge/ot-chou-orlandi",
  "edge/ot-dummy",
  "edge/ot-noar-pinkas",
  "edge/ot-test",
  "edge/ot-traits",
  "edge/polynomial",
  "edge/popsicle",
  "edge/rng",
  "edge/schmivitz",
  "edge/sieve-ir-api",
  "edge/sieve-ir-codegen",
  "edge/simple-arith-circuit",
  "edge/svole-wykw",
  "edge/twopac",
  "edge/zkv",
]

[workspace.package]
authors = ["swanky authors <swanky@galois.com>"]
license = "MIT"
edition = "2024"
publish = false
version = "0.6.0"

[workspace.lints.clippy]
assertions_on_constants = "allow"
derived_hash_with_manual_eq = "allow"
type_complexity = "allow"

[workspace.dependencies]
# Don't remove, or modify, the below "# BEGIN OUR CRATES" line. It's used by ./swanky new-crate
# BEGIN OUR CRATES
diet-mac-and-cheese = { path = "edge/diet-mac-and-cheese" }
fancy-analyzer = { path = "edge/fancy-analyzer" }
fancy-circuits = { path = "edge/fancy-circuits" }
fancy-garbling = { path = "edge/fancy-garbling" }
fancy-plaintext = { path = "edge/fancy-plaintext" }
fancy-traits = { path = "edge/fancy-traits" }
humidor = { path = "edge/humidor" }
inferno = { path = "edge/inferno" }
keyed_arena = { path = "edge/keyed_arena" }
mac-n-cheese-compiler = { path = "edge/mac-n-cheese/compiler" }
mac-n-cheese-event-log = { path = "edge/mac-n-cheese/event-log" }
mac-n-cheese-inspector = { path = "edge/mac-n-cheese/inspector" }
mac-n-cheese-ir = { path = "edge/mac-n-cheese/ir" }
mac-n-cheese-runner = { path = "edge/mac-n-cheese/runner" }
mac-n-cheese-sieve-parser = { path = "edge/mac-n-cheese/sieve-parser" }
mac-n-cheese-vole = { path = "edge/mac-n-cheese/vole" }
mac-n-cheese-wire-map = { path = "edge/mac-n-cheese/wire-map" }
popsicle = { path = "edge/popsicle" }
schmivitz = { path = "edge/schmivitz" }
simple-arith-circuit = { path = "edge/simple-arith-circuit" }
swanky-adversary = { path = "core/adversary" }
swanky-authenticated-bits = { path = "edge/authenticated-bits" }
swanky-authenticated-garbling = { path = "edge/authenticated-garbling" }
swanky-bit-matrix-transpose = { path = "edge/bit-matrix-transpose" }
swanky-block = { path = "edge/block" }
swanky-bytearray-utils = { path = "edge/bytearray-utils" }
swanky-channel = { path = "core/channel" }
swanky-channel-legacy = { path = "edge/channel-legacy" }
swanky-cointoss = { path = "edge/cointoss" }
swanky-cr-hash = { path = "edge/cr-hash" }
swanky-deprecated-bitwise-utils = { path = "edge/deprecated-bitwise-utils" }
swanky-error = { path = "core/error" }
swanky-f-eq = { path = "edge/f-eq" }
swanky-f-rand = { path = "edge/f-rand" }
swanky-field = { path = "edge/field" }
swanky-field-binary = { path = "edge/field-binary" }
swanky-field-f61p = { path = "edge/field-f61p" }
swanky-field-ff-primes = { path = "edge/field-ff-primes" }
swanky-field-fft = { path = "edge/field-fft" }
swanky-field-test = { path = "edge/field-test" }
swanky-flatbuffer-build = { path = "edge/flatbuffer-build" }
swanky-malicious-hooks = { path = "edge/malicious-hooks" }
swanky-garbled-nn = { path = "edge/garbled-nn" }
swanky-ocelot-error = { path = "edge/ocelot-error" }
swanky-oprf-kkrt = { path = "edge/oprf-kkrt" }
swanky-oprf-kmprt = { path = "edge/oprf-kmprt" }
swanky-oprf-traits = { path = "edge/oprf-traits" }
swanky-ot-alsz-kos = { path = "edge/ot-alsz-kos" }
swanky-ot-chou-orlandi = { path = "edge/ot-chou-orlandi" }
swanky-ot-dummy = { path = "edge/ot-dummy" }
swanky-ot-noar-pinkas = { path = "edge/ot-noar-pinkas" }
swanky-ot-test = { path = "edge/ot-test" }
swanky-ot-traits = { path = "edge/ot-traits" }
swanky-party = { path = "core/party" }
swanky-polynomial = { path = "edge/polynomial" }
swanky-rng = { path = "edge/rng" }
swanky-serialization = { path = "core/serialization" }
swanky-sieve-ir-api = { path = "edge/sieve-ir-api" }
swanky-sieve-ir-codegen = { path = "edge/sieve-ir-codegen" }
swanky-svole-wykw = { path = "edge/svole-wykw" }
swanky-twopac = { path = "edge/twopac" }
vectoreyes = { path = "core/vectoreyes" }
web-mac-n-cheese-wasm = { path = "edge/diet-mac-and-cheese/web-mac-and-cheese/wasm" }
web-mac-n-cheese-websocket = { path = "edge/diet-mac-and-cheese/web-mac-and-cheese/websocket" }
zkv = { path = "edge/zkv" }
# END OUR CRATES
# Don't remove, or modify, the above "# END OUR CRATES" line. It's used by ./swanky new-crate

# Patched Dependencies
ff = { git = "https://github.com/GaloisInc/ff", rev = "91d0746bdfd3b5a3ca2bfca71271e47d5f1e25de" }
ff_codegen = { git = "https://github.com/GaloisInc/ff", rev = "91d0746bdfd3b5a3ca2bfca71271e47d5f1e25de" }

# External Dependencies
aes = "0.9.2"
aes-gcm = "0.11.0"
arc-swap = "1.9.2"
arrayvec = "0.7.8"
bincode = "=1.3.3" # See https://sr.ht/~stygianentity/bincode/
bitpacking = "0.9.3"
bitvec = { version = "1.1.1", features = ["alloc"] }
# We disable avx512 since we typically run on skylake.
blake3 = { version = "1.8.7", features = ["no_avx512"] }
bufstream = "0.1.4"
bumpalo = "3.20.3"
bumpalo-herd = "0.1.3"
bytemuck = { version = "1.25.2", features = [
  "derive",
  "min_const_generics",
  "extern_crate_alloc",
  "aarch64_simd",
] }
bytes = "1.12.1"
cc = "1.4.3"
ciborium = "0.2.2"
clap = { version = "4.6.6", features = ["derive"] }
console_error_panic_hook = "0.1.7"
console_log = { version = "1.1", features = ["color"] }
criterion = "0.8.2"
crossbeam = "0.8.4"
crossbeam-queue = "0.3.13"
crypto-bigint = { version = "0.7.5", features = ["hybrid-array", "subtle"] }
curve25519-dalek = { version = "5.0.0", features = ["rand_core"] }
dhat = "0.3.3"
digest = "0.11.3"
env_logger = "0.11.11"
flatbuffers = "25.12.19" # Keep this version in sync with edge/flatbuffer-build/src/flatc-ver.txt
flume = "0.12.0"
generic-array = { version = "1.4.5", features = ["serde"] }
hex = "0.4.3"
io-uring = "0.7.14"
itertools = "0.15.0"
jemallocator = "0.5.4"
libc = "0.2.189"
log = "0.4.33"
lz4 = "1.28.1"
memchr = "2.8.3"
memmap2 = "0.9.11"
merkle-cbt = "0.3.2"
merlin = "3.0.0"
mimalloc = { version = "0.1.52", default-features = false }
moka = { version = "0.12.16", features = ["sync"] }
ndarray = "0.17.2"
# Rather than enabling nix features on a per-crate basis (which could lead to issues where
# compiling the whole workspace might succeed, but compiling an individual crate might fail),
# we just enable all the features we need at the workspace root.
nix = { version = "0.31.3", features = ["sched"] }
num-bigint = "0.5.1"
num_cpus = "1.17.0"
num-traits = "0.2.19"
parking_lot = "0.12.5"
pretty_env_logger = "0.5"
prettyplease = "0.3.0"
proc-macro2 = "1.0.107"
proptest = "1.11.0"
quick-xml = "0.41.0"
quote = "1.0.47"
rand = "0.10.2"
rand_chacha = "0.10.0"
rand_core = "0.10.1"
rayon = "1.12.0"
regex = "1.13.1"
ring = "0.17.14"
rpmalloc = "0.2.2"
rustc-hash = "2.1.3"
rustls = { version = "0.23.43", default-features = false, features = [
  "std",
  "ring",
] }
rustls-pemfile = "2.2.0"
serde = "1.0.229"
serde_json = "1.0.151"
sha2 = "0.11.0"
sha3 = "0.12.0"
shake = "0.1.0"
smallvec = { version = "1.15.2", features = [
  "const_generics",
  "union",
  "const_new",
] }
snafu = "0.9.2"
snmalloc-rs = { version = "0.7.5", default-features = false, features = [
  "build_cc",
  "usecxx17",
] }
sprs = "0.11.5"
subtle = { version = "2.6.1", features = [
  "core_hint_black_box",
  "const-generics",
] }
syn = { version = "3.0.3", features = ["full"] }
tempfile = "3.27.0"
toml = "1.1.4"
tungstenite = { version = "0.30.0", features = ["rustls"] }
twox-hash = "2.1.3"
wasm-bindgen = "0.2.127"
zstd = "0.13.3"

[profile.release]
opt-level = 3
debug = true
lto = true
debug-assertions = false
overflow-checks = false
codegen-units = 1

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = true
lto = true
debug-assertions = false
overflow-checks = false

[profile.test]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.dev.package]
# See #147
jemalloc-sys.opt-level = 3
