[package]
name = "mac-n-cheese-vole"
description = "An implementation of Vector Oblivious Linear Evaluation"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
scuttlebutt.workspace = true
ocelot.workspace = true
vectoreyes.workspace = true
generic-array.workspace = true
bytemuck.workspace = true
eyre.workspace = true
rand.workspace = true
keyed_arena.workspace = true
blake3.workspace = true
arrayvec.workspace = true
swanky-party.workspace = true

[dev-dependencies]
rand.workspace = true
scuttlebutt.workspace = true
mimalloc.workspace = true

[[bench]]
name = "vole"
harness = false

