/*!
Convert vector commitments to VOLEs.
*/
use crate::vole::crypto_primitives::{IV, Prg, Seed};
use rand::RngExt;
use swanky_field_binary::{F2, F8b};

/// Convert seeds to VOLEs for the prover.
///
/// It corresponds to `ConvertToVOLE` (Figure 5.6 in the FAEST spec v2.0).
pub(crate) fn convert_to_vole_prover(
    seeds: [Seed; 256],
    iv: IV,
    l_hat: usize,
) -> (Vec<F2>, Vec<F8b>) {
    convert_to_vole::<true>(seeds, iv, l_hat)
}

/// Convert seeds to VOLEs.
///
/// Corresponds to `ConvertToVOLE` (Figure 5.6 in the FAEST spec v2.0). It
/// differs from the naive algorithm by relying exclusively on xor operations on
/// packed binary field values.
fn convert_to_vole<const IS_PROVER: bool>(
    seeds: [Seed; 256],
    iv: IV,
    l_hat: usize,
) -> (Vec<F2>, Vec<F8b>) {
    // The number of random seeds. This corresponds to `N` in the spec.
    const N: usize = 256;
    // The tree depth. This corresponds to `d` in the spec.
    const DEPTH: usize = 8;

    let mut u_res = Vec::with_capacity(l_hat);
    let mut v_res = Vec::with_capacity(l_hat);

    let mut prgs = seeds.map(|seed| Prg::new(seed, iv));

    // `r` is only the last 2 layers of the original structure from the spec.
    // Only 2 layers are used using a swap operation in the loop.
    // Again, u64 to do 64 boolean/bit operations at once.
    let mut r0 = [0; N];
    let mut r1 = [0; N];
    let mut remaining = l_hat;

    // Precompute an array of 2*i indices and another array for 2*i+1.
    // This is faster (by about 0.15ms for the HMAC circuit) than computing the
    // values directly in the loop below.
    //
    // TODO: Make `const`s once `from_fn` is stabilized as a `const fn`.
    let i2_arr: [usize; 128] = core::array::from_fn(|i| i * 2);
    let i2_plus_1_arr: [usize; 128] = core::array::from_fn(|i| i * 2 + 1);

    // Construct `u` and `v`s 64 bits at a time.
    for _ in 0..=l_hat / 64 {
        let mut v = [0; DEPTH];
        // Fill `r0` with random `u64`s generated by each PRG.
        for i in 0..N {
            if i != 0 || IS_PROVER {
                r0[i] = prgs[i].random::<u64>();
            }
        }

        let mut i_bound = 128;
        // Lines 6-9.
        #[allow(clippy::needless_range_loop)]
        for j in 0..DEPTH {
            // Lines 7-9.
            for i in 0..i_bound {
                v[j] ^= r0[i2_plus_1_arr[i]];
                r1[i] = r0[i2_arr[i]] ^ r0[i2_plus_1_arr[i]];
            }

            // swap the top-level to the lower level
            r0[0..i_bound].copy_from_slice(&r1[0..i_bound]);

            i_bound /= 2;
        }

        let u = r0[0];
        for i in 0..core::cmp::min(64, remaining) {
            u_res.push(((u >> i & 1) == 1).into());
            let mut x = 0u8;
            #[allow(clippy::needless_range_loop)]
            for j in 0..DEPTH {
                x |= ((v[j] >> i & 1) as u8) << j;
            }
            v_res.push(F8b::from(x));
        }
        remaining -= core::cmp::min(64, remaining);
        if remaining == 0 {
            break;
        }
    }
    debug_assert_eq!(u_res.len(), l_hat);
    debug_assert_eq!(v_res.len(), l_hat);
    (u_res, v_res)
}

#[cfg(test)]
/// This function is the naive version of [`convert_to_vole`] that does not
/// operate on packed boolean field values.
fn convert_to_vole_prover_naive(seeds: [Seed; 256], iv: IV, l_hat: usize) -> (Vec<F2>, Vec<F8b>) {
    use swanky_field::FiniteRing;

    let mut u_res = vec![F2::ZERO; l_hat];
    let mut v_res = vec![F8b::ZERO; l_hat];

    let mut i = 0u8;
    for seed in seeds {
        let mut prg = Prg::new(seed, iv);

        // Generate u64 items to match the use in `convert_to_vole`.
        let randoms = (0..l_hat / 64 + 1)
            .map(|_| prg.random::<u64>())
            .collect::<Vec<_>>();
        let mut v = Vec::with_capacity(l_hat);
        for block in randoms {
            for i in 0..64 {
                let bit = ((block >> i) & 1) == 1;
                v.push(F2::from(bit));
            }
        }
        v.truncate(l_hat);
        let i_f8b = F8b::from(i);
        for (j, r) in v.iter().enumerate() {
            u_res[j] += r;
            v_res[j] += *r * i_f8b;
        }
        i = i.wrapping_add(1);
    }

    (u_res, v_res)
}

/// Convert seeds to VOLEs for the verifier.
///
/// It corresponds to `ConvertToVOLE` (Figure 5.6 in the FAEST spec v2.0), with
/// additional permutation of the seeds by $`\Delta`$.
pub(crate) fn convert_to_vole_verifier(
    seeds: [Seed; 256],
    iv: IV,
    l_hat: usize,
    delta: u8,
) -> Vec<F8b> {
    // Permutate the seeds according to `delta`, with the permutation
    // `i` -> `i xor delta`.
    let seeds_permuted: [_; 256] = core::array::from_fn(|i| {
        let idx: u8 = (i as u8) ^ delta;
        if i != 0 {
            seeds[idx as usize]
        } else {
            Seed::default()
        }
    });
    let (_, v) = convert_to_vole::<false>(seeds_permuted, iv, l_hat);
    v
}

#[cfg(test)]
fn convert_to_vole_verifier_naive(seeds: [Seed; 256], iv: IV, l_hat: usize, delta: u8) -> Vec<F8b> {
    use swanky_field::FiniteRing;

    let mut v_res = vec![F8b::ZERO; l_hat];

    let mut i = 0u8;

    for (j, seed) in seeds.into_iter().enumerate() {
        if j != delta as usize {
            let mut prg = Prg::new(seed, iv);

            // Generate u64 items to match the use in `convert_to_vole`.
            let randoms = (0..l_hat / 64 + 1)
                .map(|_| prg.random::<u64>())
                .collect::<Vec<_>>();
            let mut v = Vec::with_capacity(l_hat);
            for block in randoms {
                for i in 0..64 {
                    let bit = ((block >> i) & 1) == 1;
                    v.push(F2::from(bit));
                }
            }
            v.truncate(l_hat);

            let i_f8b = F8b::from(i);
            let delta_f8b = F8b::from(delta);
            for (j, r) in v.iter().enumerate() {
                v_res[j] += *r * (delta_f8b - i_f8b);
            }
        } else {
            assert_eq!(seed, Seed::default());
        }
        i = i.wrapping_add(1);
    }

    v_res
}

#[cfg(test)]
mod test {
    use super::{convert_to_vole_prover_naive, convert_to_vole_verifier_naive};
    use crate::vole::{
        convert_to_vole::convert_to_vole_prover,
        crypto_primitives::{IV, Seed},
    };
    use rand::{RngExt, rng};
    use swanky_field_binary::F8b;

    #[test]
    fn test_convert_to_vole_naive() {
        let rng = &mut rng();

        let seeds: [_; 256] = core::array::from_fn(|_| rng.random::<Seed>());
        let iv = rng.random();

        let delta = 3u8;
        let how_many = 1027;
        let (u, vs) = convert_to_vole_prover_naive(seeds, iv, how_many);

        let mut seeds_verifier = [Seed::default(); 256];
        for i in 0..256 {
            if i != (delta as usize) {
                seeds_verifier[i] = seeds[i];
            }
        }
        let qs = convert_to_vole_verifier_naive(seeds_verifier, iv, how_many, delta);

        for ((u, v), q) in u.iter().zip(vs.iter()).zip(qs.iter()) {
            let delta_f8b = F8b::from(delta);
            assert_eq!(*q, (*u * delta_f8b) - *v);
        }
    }

    #[test]
    fn test_convert_to_vole() {
        let rng = &mut rng();

        let seeds: [_; 256] = core::array::from_fn(|_| rng.random::<Seed>());
        let iv = rng.random::<IV>();

        let delta = 3u8;
        let how_many = 1027;
        let (u, vs) = convert_to_vole_prover_naive(seeds, iv, how_many);

        /* This test checks the equivalence between convert_to_vole and its naive version */
        let (u_xor, v_xor) = convert_to_vole_prover(seeds, iv, how_many);
        assert_eq!(u_xor, u);
        assert_eq!(v_xor, vs);

        let mut seeds_verifier = [Seed::default(); 256];
        for i in 0..256 {
            if i != (delta as usize) {
                seeds_verifier[i] = seeds[i];
            }
        }
        let qs = convert_to_vole_verifier_naive(seeds_verifier, iv, how_many, delta);

        /* This test was to test the correspondance between the two functions */
        let qs_xor = super::convert_to_vole_verifier(seeds, iv, how_many, delta);
        assert_eq!(qs, qs_xor);

        for ((u, v), q) in u.iter().zip(vs.iter()).zip(qs.iter()) {
            let delta_f8b = F8b::from(delta);
            assert_eq!(*q, (*u * delta_f8b) - *v);
        }
    }
}
