/*! Cryptographic primitives used for VOLE-it-HEAD */
use crate::parameters::SECURITY_PARAM;
use crate::vole::commit_reconstruct::{Corrections, corrections_to_bytes};
use rand::{Rng, SeedableRng, TryRng, rand_core::Infallible};
use sha3::digest::{ExtendableOutput, Update, XofReader};
use shake::Shake128;
use swanky_field_binary::F128b;
use swanky_rng::SwankyRng;
use swanky_serialization::CanonicalSerialize;

/// Initialization Vector.
pub(crate) type IV = [u8; 16];
/// Key as found in the internal nodes of the Tree-PRG/GGM-tree.
pub(crate) type Key = [u8; SECURITY_PARAM / 8];
/// Commitment as generated by 1-VC.
pub(crate) type Com = [u8; (SECURITY_PARAM * 2) / 8];
/// Seed generated by 1-VC.
pub(crate) type Seed = [u8; SECURITY_PARAM / 8];

/// The PRG used by VOLE-in-the-Head.
///
/// This is a thin wrapper around [`SwankyRng`], which itself implements a
/// AES-CTR-based PRG as defined in the FAEST spec.
pub(crate) struct Prg(SwankyRng);

impl Prg {
    /// Create a new [`Prg`] using the provided [`Seed`] and [`IV`].
    pub(crate) fn new(seed: Seed, iv: IV) -> Self {
        Self(SwankyRng::from_seed_and_iv(
            seed.into(),
            u128::from_le_bytes(iv),
        ))
    }

    /// Create a new [`Prg`] using the provided [`Seed`].
    pub(crate) fn new_no_iv(seed: Seed) -> Self {
        Self(SwankyRng::from_seed(seed.into()))
    }
}

impl TryRng for Prg {
    type Error = Infallible;

    fn try_next_u32(&mut self) -> Result<u32, Self::Error> {
        Ok(self.0.next_u32())
    }

    fn try_next_u64(&mut self) -> Result<u64, Self::Error> {
        Ok(self.0.next_u64())
    }

    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), Self::Error> {
        self.0.try_fill_bytes(dest)
    }
}

#[cfg(test)]
mod tests {
    use super::IV;
    use rand::RngExt;
    use swanky_field_binary::F2;
    use swanky_rng::SwankyRng;

    #[test]
    fn swanky_prg_matches_stream_bits() {
        let seed: IV = [5u8; 16];
        let iv: IV = [11u8; 16];

        let lengths = [
            1, 7, 8, 63, 64, 65, 127, 128, 129, 511, 512, 513, 1023, 1024, 1025, 2047, 2048, 2049,
            100000, 1048575, 1048576, 1048577,
        ];
        for &l in &lengths {
            let mut rng = SwankyRng::from_seed_and_iv(seed.into(), u128::from_le_bytes(iv));
            let randoms = (0..l / 64 + 1)
                .map(|_| rng.random::<u64>())
                .collect::<Vec<_>>();
            let mut expected_bits = Vec::with_capacity(l);
            for block in randoms {
                for i in 0..64 {
                    let bit = ((block >> i) & 1) == 1;
                    expected_bits.push(F2::from(bit));
                }
            }
            expected_bits.truncate(l);
            let mut stream = SwankyRng::from_seed_and_iv(seed.into(), u128::from_le_bytes(iv));
            // let mut stream = PRG_Stream::new(seed, iv);
            let mut stream_bits = Vec::with_capacity(l);
            while stream_bits.len() < l {
                let block = stream.random::<u64>();
                for i in 0..64 {
                    if stream_bits.len() == l {
                        break;
                    }
                    let bit = ((block >> i) & 1) == 1;
                    stream_bits.push(F2::from(bit));
                }
            }
            assert_eq!(expected_bits, stream_bits, "bit mismatch for l={}", l);
        }
    }
}

/// Hash function that generates a [`Seed`] and a [`Com`]mitment from a [`Key`] and an initialization vector [`IV`].
///
/// This function is applied on the leaves keys of the Tree-PRG/GGM-tree to generate the seeds and commitments.
/// This function corresponds to the H0 in the FAEST spec, defined page 16.
pub(crate) fn h0(x: Key, iv: IV) -> (Seed, Com) {
    // Hash x||iv to generate the Key
    let mut hasher = Shake128::default();
    hasher.update(&x);
    hasher.update(&iv);
    hasher.update(&[0u8]);

    let mut reader = hasher.finalize_xof();
    let mut seed = [u8::default(); SECURITY_PARAM / 8];
    let mut commitment = [u8::default(); (SECURITY_PARAM * 2) / 8];
    reader.read(seed.as_mut_slice());
    reader.read(commitment.as_mut_slice());

    (seed, commitment)
}

/// Length of H1 hash in bytes.
pub(crate) const H1_LENGTH: usize = (SECURITY_PARAM / 8) * 2;

/// Hash digest for a collision-resistant hash function.
///
/// This is used for various purposes throughout the protocol.
#[derive(Clone, Copy, Default)]
pub(crate) struct H1(pub [u8; H1_LENGTH]);

impl H1 {
    /// Compute the [`H1`] hash from input bytes.
    pub(crate) fn from_bytes(inp: &[u8]) -> H1 {
        let mut out = H1::default();

        let mut hasher = Shake128::default();
        hasher.update(inp);
        hasher.update(&[1u8]);

        hasher.finalize_xof_into(&mut out.0);
        out
    }

    /// Treat this hash digest as a commitment.
    pub(crate) fn into_com(self) -> Com {
        self.0
    }
}

impl AsRef<[u8; H1_LENGTH]> for H1 {
    fn as_ref(&self) -> &[u8; H1_LENGTH] {
        &self.0
    }
}

/// Hash function for the Fiat-Shamir challenges generated in the protocol.
///
/// This is `$H_2^j$` in FAEST spec
#[derive(Default)]
struct H2Hasher(Shake128);

impl H2Hasher {
    fn update(&mut self, data: &[u8]) {
        self.0.update(data);
    }

    fn finalize(mut self, out: &mut [u8]) {
        self.0.update(&[2u8]);
        self.0.finalize_xof_into(out);
    }
}

/// Length of 1st challenge in bytes.
pub(crate) const CHALL1_LENGTH: usize = (SECURITY_PARAM * 6) / 8;

/// First challenge
pub(crate) type Chall1 = [u8; CHALL1_LENGTH];

/// Make the first Fiat-Shamir challenge.
///
/// This computes `$H_2^1$` in FAEST spec.
pub(crate) fn h2_chall1(mu: &H1, hcom: &Com, corrections: &Corrections, iv: &IV) -> Chall1 {
    let mut hasher = H2Hasher::default();

    hasher.update(&mu.0);
    hasher.update(hcom);
    hasher.update(&corrections_to_bytes(corrections));
    hasher.update(iv);

    let mut out = [0u8; CHALL1_LENGTH];
    hasher.finalize(&mut out);
    out
}

/// Length of 2nd challenge in bytes.
pub(crate) const CHALL2_LENGTH: usize = (SECURITY_PARAM * 3 + 64) / 8;
/// Second challenge
pub(crate) type Chall2 = [u8; CHALL2_LENGTH];

/// This is `$H_2^2$` in FAEST spec.
#[allow(unused)]
pub(crate) fn h_chall2(inp: &[u8]) -> Chall2 {
    let mut hasher = H2Hasher::default();

    hasher.update(inp);

    let mut out: Chall2 = [0u8; CHALL2_LENGTH]; // NOTE: default does not work here
    hasher.finalize(&mut out);
    out
}

/// Length of 3rd challenge in bytes.
pub(crate) const CHALL3_LENGTH: usize = SECURITY_PARAM / 8;
/// Third challenge.
pub(crate) type Chall3 = [u8; CHALL3_LENGTH];

/// Makes the third Fiat-Shamir challenge.
///
/// This computes `$H_2^3$` in FAEST spec.
#[allow(unused)]
pub(crate) fn h2_chall3(chall2: &Chall2, a_tilde: &F128b, b_tilde: &F128b) -> Chall3 {
    let mut hasher = H2Hasher::default();

    hasher.update(chall2);
    hasher.update(&a_tilde.to_bytes());
    hasher.update(&b_tilde.to_bytes());

    let mut out = Chall3::default();
    hasher.finalize(&mut out);
    out
}

/// Hash digest for randomness and IV generation.
///
/// This should incorporate secret information or randomness (e.g. that only
/// the verifier knows), to derive secret, per-proof values.
#[derive(Clone, Default)]
pub(crate) struct H3([u8; (SECURITY_PARAM + 128) / 8]);

impl H3 {
    /// Derive the [`H3`] hash from an input.
    #[allow(unused)]
    pub(crate) fn from_input(inp: &[u8]) -> Self {
        let mut hasher = Shake128::default();
        hasher.update(inp);

        // Append 0x3 for domain separation
        hasher.update(&[3u8]);
        let mut reader = hasher.finalize_xof();

        let mut out: H3 = Default::default();
        reader.read(out.as_mut());
        out
    }

    /// Derive the [`H3`] hash from an instance of `Shake128`, which we assume
    /// has already been updated with all relevant secret information.
    pub(crate) fn from_xof(mut xof: Shake128) -> Self {
        // Append 0x3 for domain separation
        xof.update(&[3u8]);

        let mut out: H3 = Default::default();
        xof.finalize_xof_into(out.as_mut());
        out
    }
}

impl AsRef<[u8; SECURITY_PARAM / 8 + 128 / 8]> for H3 {
    fn as_ref(&self) -> &[u8; SECURITY_PARAM / 8 + 128 / 8] {
        &self.0
    }
}

impl AsMut<[u8; SECURITY_PARAM / 8 + 128 / 8]> for H3 {
    fn as_mut(&mut self) -> &mut [u8; SECURITY_PARAM / 8 + 128 / 8] {
        &mut self.0
    }
}
