[package]
name = "swanky-ot-noar-pinkas"
description = "An implementation of the Noar-Pinkas OT protocol"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
swanky-adversary.workspace = true
swanky-block.workspace = true
swanky-channel-legacy.workspace = true
swanky-error.workspace = true
swanky-ot-traits.workspace = true

curve25519-dalek.workspace = true
rand.workspace = true
blake3.workspace = true

[dev-dependencies]
swanky-ot-test.workspace = true
criterion.workspace = true

[[bench]]
name = "ot"
harness = false
