[package]
name = "inferno"
description = "An implementation of the Limbo zero knowledge proof protocol"
keywords = ["cryptography", "zero-knowledge", "nizk"]
categories = ["cryptography"]
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
bincode.workspace = true
blake3.workspace = true
generic-array.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
rayon.workspace = true
swanky-rng.workspace = true
swanky-block.workspace = true
swanky-error.workspace = true
swanky-field.workspace = true
swanky-polynomial.workspace = true
swanky-serialization.workspace = true
serde = { workspace = true, features = ["derive"] }
simple-arith-circuit = { workspace = true, features = ["serde"] }

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
criterion.workspace = true
proptest.workspace = true
serde_json.workspace = true
env_logger.workspace = true
swanky-field-binary.workspace = true
swanky-field-ff-primes.workspace = true

[[bench]]
name = "random_circuit"
harness = false

[[example]]
name = "inferno"
