[package]
name = "swanky-authenticated-garbling"
description = "Authenticated malicious garbling in the presence of a malicious garbler and evaluator"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
fancy-analyzer.workspace = true
fancy-traits.workspace = true
fancy-garbling.workspace = true
swanky-authenticated-bits.workspace = true
swanky-field.workspace = true
swanky-field-binary.workspace = true
swanky-channel.workspace = true
swanky-party.workspace = true
swanky-rng.workspace = true
swanky-error.workspace = true
swanky-serialization.workspace = true
vectoreyes.workspace = true

rand.workspace = true

[dev-dependencies]
fancy-circuits.workspace = true
fancy-plaintext.workspace = true

criterion.workspace = true

[[bench]]
name = "main"
harness = false

[[example]]
name = "gates_per_sec"
