[package]
name = "swanky-ot-traits"
description = "Base traits for Obliivious Transfer protocols"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
swanky-channel-legacy.workspace = true
swanky-error.workspace = true

rand.workspace = true
