[package]
name = "mac-n-cheese-vole"
description = "An implementation of Vector Oblivious Linear Evaluation"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
swanky-ot-alsz-kos.workspace = true
swanky-svole-wykw.workspace = true

vectoreyes.workspace = true
hybrid-array.workspace = true
bytemuck.workspace = true
rand.workspace = true
keyed_arena.workspace = true
blake3.workspace = true
arrayvec.workspace = true
swanky-rng.workspace = true
swanky-block.workspace = true
swanky-channel-legacy.workspace = true
swanky-cointoss.workspace = true
swanky-error.workspace = true
swanky-field.workspace = true
swanky-field-binary.workspace = true
swanky-field-f61p.workspace = true
swanky-field-ff-primes.workspace = true
swanky-party.workspace = true
swanky-serialization.workspace = true

[dev-dependencies]
rand.workspace = true
mimalloc.workspace = true

[[bench]]
name = "vole"
harness = false

