[package]
name = "fancy-circuits"
readme = "README.md"
description = "Circuits implementing the `Fancy` API"
categories = ["cryptography"]
keywords = ["cryptography", "secure computation"]
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
serde = ["dep:serde"]

[dependencies]
fancy-plaintext.workspace = true
fancy-traits.workspace = true
swanky-channel.workspace = true
swanky-error.workspace = true
swanky-field.workspace = true
swanky-field-binary.workspace = true

rand.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
fancy-plaintext.workspace = true
fancy-garbling.workspace = true
swanky-rng.workspace = true
