[package]
name = "swanky-oprf-kmprt"
description = "An implementation of the KMPRT OPRF protocol"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
swanky-adversary.workspace = true
swanky-block.workspace = true
swanky-channel-legacy.workspace = true
swanky-error.workspace = true
swanky-oprf-kkrt.workspace = true
swanky-oprf-traits.workspace = true
vectoreyes.workspace = true

rand.workspace = true

[dev-dependencies]
swanky-rng.workspace = true

criterion.workspace = true
proptest.workspace = true

[[bench]]
name = "oprf"
harness = false
