[package]
name = "swanky-field-fft"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
swanky-field.workspace = true
