#!/bin/bash -e

nparties=3
config_file="secretsister.yaml"
input_file="test_inputs"
port=6666
setsize=128

usage() {
    echo "$0"
    echo "PSI local test script" 
    echo "      -h          this message"
    echo "      -p NUM      run test with NUM local parties [$nparties]"
    echo "      -n NUM      run test with setsize NUM [$setsize]"
}

while getopts "hp:n:" opt; do
    case $opt in 
        h) usage && exit 0;;
        p) nparties=$OPTARG;;
        n) setsize=$OPTARG;;
        *) usage && exit 1;;
    esac
done

shift $((OPTIND-1))

################################################################################
## set up config file

cat << EOF > $config_file
- Receiver:
    address: localhost
    port: $port
EOF

for party in $(seq 1 $((nparties-1))); do
cat << EOF >> $config_file
- Sender:
    address: localhost
    port: $((port + party))
EOF
done

################################################################################
## generate test input

echo "generating test input"

perl -E "
for (1..$setsize) {
    printf \"%04X\", rand(65536);
    for (1..7) {
        printf \":%04X\", rand(65536);
    }
    say \"\";
}
" > $input_file

################################################################################
## run tests

cmd="cargo run --all-features --release --quiet --example secretsister -- "

# senders
for party in $(seq 1 $((nparties - 1))); do
    echo "creating sender $party"
    $cmd $party $input_file 2>&1 > /dev/null &
done

# receiver
$cmd 0 $input_file
