#!/bin/bash -e

nparties=3
config_file="secretsister.yaml"
input_file="test_inputs"
port=6666
setsize=128

usage() {
    echo "$0"
    echo "PSI local test script" 
    echo "      -h          this message"
    echo "      -p NUM      run test with NUM local parties [$nparties]"
    echo "      -s NUM      run test with setsize NUM [$setsize]"
}

while getopts "hp:s:" opt; do
    case $opt in 
        h) usage && exit 0;;
        p) nparties=$OPTARG;;
        s) setsize=$OPTARG;;
        *) usage && exit 1;;
    esac
done

shift $((OPTIND-1))

################################################################################
## set up config file

cat << EOF > $config_file
- Receiver:
    address: localhost
    port: $port
EOF

for party in $(seq 1 $((nparties-1))); do
cat << EOF >> $config_file
- Sender:
    address: localhost
    port: $((port + party))
EOF
done

################################################################################
## generate test input

rm -f $input_file

for i in $(seq $((setsize - 1))); do
    printf "%04X" $RANDOM >> $input_file
    for j in $(seq 1 7); do
        printf ":%04X" $RANDOM >> $input_file
    done
    echo >> $input_file
done

################################################################################
## run tests

cmd="cargo run --all-features --release --example secretsister -- "

tmux new-session -d -s secretsister "$cmd 0 $input_file"

for party in $(seq 1 $((nparties - 1))); do
    tmux split-window "-v" "$cmd $party $input_file"
done

tmux attach-session -t secretsister
