[package]
name = "swanky-flatbuffer-build"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
blake3.workspace = true
tempfile.workspace = true
