[package]
name = "swanky-generic-array"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
generic-array.workspace = true

